# Generated by Django 5.0.7 on 2025-02-28 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchhistory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='WatchHistory',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
